# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170905_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_nr',
            field=models.CharField(blank=True, help_text='Format: +38611111111', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefonska mora biti v formatu "+999999999".                                        Dovoljenih do 15 znakov.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
