# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboj', '0005_auto_20170908_1117'),
        ('users', '0003_auto_20170905_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dislikes',
            field=models.ManyToManyField(related_name='user_dislikes', to='zaboj.Vegetable'),
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='user_likes', to='zaboj.Vegetable'),
        ),
    ]
