# Generated by Django 2.0 on 2017-12-24 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171221_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('street_name', models.CharField(blank=True, max_length=120, null=True)),
                ('street_nr', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('vat_nr', models.PositiveIntegerField()),
                ('vat_taxpayer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('street_name', models.CharField(blank=True, max_length=120, null=True)),
                ('street_nr', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
