# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zaboj', '0007_crate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabojDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_received', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_extra_donation', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZabojProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_notes', models.TextField(max_length=140)),
                ('enduser_notes', models.TextField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('crate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaboj.Crate')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaboj.Order')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZabojStorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zaboj.Order')),
            ],
        ),
        migrations.AddField(
            model_name='zabojdistribution',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ZabojProduction'),
        ),
    ]
