# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170908_1117'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabojproduction',
            name='assign_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.Distributer'),
            preserve_default=False,
        ),
    ]
