# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
