# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaboj', '0003_auto_20170906_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPreferences',
            new_name='UserPreference',
        ),
    ]
