# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaboj', '0005_auto_20170908_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='vegetable',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
