# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboj', '0006_auto_20170909_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('at_user', models.BooleanField(default=False)),
                ('in_repairs', models.BooleanField(default=False)),
            ],
        ),
    ]
