# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 22:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170908_1117'),
        ('zaboj', '0007_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crate',
            name='at_distributer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Distributer'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='at_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
