# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaboj', '0008_auto_20170917_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crate',
            name='at_distributer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Distributer'),
        ),
        migrations.AlterField(
            model_name='crate',
            name='at_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
