# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboj', '0009_auto_20170917_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(help_text='Max 400 znakov.', max_length=400, verbose_name='Opombe'),
        ),
    ]
