# Generated by Django 2.0 on 2017-12-24 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('street_name', models.CharField(blank=True, max_length=120, null=True)),
                ('street_nr', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('vat_nr', models.PositiveIntegerField()),
                ('vat_taxpayer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount_for_returned_package', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delivery_method', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('arrived', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=120, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_decimal_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_package', models.CharField(blank=True, max_length=120, null=True)),
                ('item_package_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_package_tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('item_package_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('street_name', models.CharField(blank=True, max_length=120, null=True)),
                ('street_nr', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
        ),
    ]
