# Generated by Django 2.0 on 2017-12-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_tax_bracket',
            field=models.DecimalField(decimal_places=2, default=22, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_unit_of_measure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
