# Generated by Django 2.0 on 2017-12-26 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20171226_0104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingAddress',
            new_name='OrderBillingAddress',
        ),
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='OrderShippingAddress',
        ),
    ]
