# Generated by Django 2.0 on 2017-12-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20171226_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_package_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
