# Generated by Django 2.0 on 2017-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_item_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbillingaddress',
            name='company_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
