# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171212_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='tax_bracket',
            field=models.DecimalField(decimal_places=2, default='22', max_digits=4),
        ),
    ]
