# Generated by Django 2.0 on 2017-12-29 11:50

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_variation_package_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('varbose_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('varbose_name', models.CharField(max_length=120)),
                ('options', models.ManyToManyField(to='products.ProductOption')),
            ],
        ),
        migrations.CreateModel(
            name='VariationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.image_upload_to)),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variation')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='option_groups',
            field=models.ManyToManyField(to='products.ProductOptionGroup'),
        ),
        migrations.AddField(
            model_name='variation',
            name='options',
            field=models.ManyToManyField(to='products.ProductOption'),
        ),
    ]
