# Generated by Django 2.0 on 2017-12-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20171229_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='varbose_name',
            new_name='verbose_name',
        ),
        migrations.RenameField(
            model_name='productoptiongroup',
            old_name='varbose_name',
            new_name='verbose_name',
        ),
    ]
