# Generated by Django 2.0 on 2017-12-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171229_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptiongroup',
            name='options',
            field=models.ManyToManyField(db_constraint=False, to='products.ProductOption'),
        ),
    ]
